#!/bin/bash
#export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
# firefox enable touchscreen
export MOZ_USE_XINPUT2=1
# firefox enable wayland
export MOZ_ENABLE_WAYLAND=1
#export XWAYLAND_SCALE=1
export ELECTRON_OZONE_PLATFORM_HINT=wayland

exec dbus-launch --exit-with-session sway      
