#!/bin/bash
export SDL_VIDEODRIVER=wayland
#export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
# firefox enable touchscreen
export MOZ_USE_XINPUT2=1
# firefox enable wayland
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
exec dbus-launch sway      
